project:
  type: website
  output-dir: docs
website:
  google-analytics: "G-N2CBRC6JPM"
  site-path: "/handbooks/"
  title: "2026/27 Options Guide"
  navbar:
    background: primary
    search: true
    left:
      - text: Home
        href: index.qmd
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Overview"
        contents:
          - introduction.qmd
          
      - section: "PSYC611"
        contents:
          - PSYC611_outline.qmd
        
      - section: "PSYC612"
        contents:
          - PSYC612_outline.qmd
          - ji.qmd
          - charlesford.qmd
          - floccia.qmd
          - mitchell.qmd
          - kuhn.qmd
          - ganis.qmd
          - atherton.qmd
          - bacon.qmd
          
      - section: "PSYC613"
        contents:
          - PSYC613_outline.qmd
          
      - section: "PSYC614"
        contents:
          - PSYC614_outline.qmd
          - or.qmd
          - pazhoohi.qmd
          - cross.qmd
          - kanngiesser.qmd
          - berry.qmd
          - tatone.qmd
          - heintz.qmd
          - pisauro.qmd

format:
  html:
    theme: united
    css: styles.css
    toc: true
    mainfont: helvetica

editor: visual

