---
title: "Academic Dishonesty"
---

Academic dishonesty includes plagiarism, collusion, cheating in exams, and fabricating data. These are the ultimate sins in academia, and they are taken very seriously by the University. If they are detected and proven, the punishments can be serious. This is necessary in order to maintain the integrity of what we do.

The University has very strict regulations about academic dishonesty. It is your responsibility to know what counts as academic dishonesty according to the University regulations, and to make sure you avoid committing any action which could be construed as dishonest.

The University provides clear guidelines, and you should look at these carefully. The guidance on examination offences is here:

<https://www.plymouth.ac.uk/student-life/your-studies/essential-information/exams/exam-rules-and-regulations/examination-offences>

Plagiarism is probably the offence we encounter most frequently. Essentially, plagiarism is about taking credit for other people's work. It does not have to be intentional; it is up to you to make sure you acknowledge the contributions of others.

You should familiarise yourself with the University's guidance on plagiarism, which you can find here:

<https://www.plymouth.ac.uk/student-life/your-studies/essential-information/regulations/plagiarism>

Information on the consequences of academic dishonesty is included here:

<https://www.plymouth.ac.uk/uploads/production/document/path/7/7518/Examination_and_Academic_Offences_procedures_.pdf>

### Preventing academic dishonesty

Everyone involved in higher education is responsible for preventing the incidence of academic dishonesty. Prime responsibility rests with students themselves. You can help reduce the incidence of academic dishonesty through following these points of principle:

· Be organised in your work. Students committing academic dishonesty often claim that time pressures and last minute panic led them to cheat. Such panic might be a reason for cheating but it does not excuse it. You can reduce the likelihood of such pressures by being organised, knowing what assessment deadlines you have to meet, and planning your work accordingly. If you are not a good organiser, take advice. Advice is available from your personal tutor, from study skills courses run by the University and from your network of friends and colleagues.

• Know the rules. It is tremendously important to know what counts as academic dishonesty. One problem is of course that there is no hard and fast cut off between honesty and dishonesty; there are gradations between best practice and utterly dishonest practice. It is essential that you get a sense of where the boundary lies on this gradation. Sometimes students plead that ignorance of the rules led them to cheat. Again this ignorance may be a reason for cheating, but it does not excuse it.

• Don't ignore dishonest practice. There are occasions where you suspect a fellow student of committing academic dishonesty. The most common form of this practice occurs where another student uses or copies your work without your permission. If you suspect that someone is cheating in this way, then you can talk to your personal tutor, the relevant marker, the relevant module leader, or programme leader all in confidence. If your suspicion is well founded then the member of staff will take steps to detect the cheating without involving you directly.

• Be aware of detection systems. The School of Psychology has systems for checking work submitted for assessments and detecting academic dishonesty. The marker is obviously in a good position to detect cheating such as plagiarism. Coursework submitted via the DLE is entered into plagiarism detection software which compares the content of each assignment with those of other students and with text on web sites and in journals and books. By being able to match the content of the essay with these different sources, this software now has a very high detection rate for plagiarism.
