---
title: "Apprenticeships"
---

The Research Apprentice scheme has been developed by The School of Psychology to let students gain research experience during the academic year. The goal of the scheme is to provide an educational experience to students in any stage of the psychology programmes by exposing them to the process of conducting cutting-edge research in "learning by doing." Students can volunteer to work on a research project under the supervision of a member of academic staff.

The scheme is unpaid, and entirely voluntary.  Apprenticeships typically consist of 4 hours per week, for ten weeks.

While the apprenticeship is totally separate from the final year project, it can provide useful experience and expertise. Students need to check with staff members who they would like to work with whether they are willing to accept students. Upon completion of the scheme students will receive a letter from the Head of School documenting their participation. For further information, please contact Dr. Chris Berry: <christopher.berry@plymouth.ac.uk>

How to become a Research Apprentice:

1.	Identify some possible Supervisors. Use the school web pages or your knowledge from lectures to find out which staff research the areas of psychology you are interested in working in. Do some background research by reading papers they have published recently.

2.	Find out if your potential supervisors are looking for apprentices this academic year. Send them an email or visit them during their office hours.
