---
title: "Assessment Overview"
---

During each year you will be required to complete and pass a number of assessments for each module. In order to progress to the next stage of the degree programme you need to pass all the modules on which you are enrolled. It is therefore important that you do well in the assessments set for each module.

In order to do well you will have to do at least the following:

*	attend your timetabled classes
*	read the class handouts and your notes
*	follow up additional reading provided by teaching staff
*	plan your work so that you have enough time to complete each assignment
*	feel confident in your reading and writing skills

If you experience problems in any of these areas or others related to your work, then you should discuss these problems with your personal tutor. They will be able to advise you on the courses of action which might help you.

A list of assessments for each stage, including relevant deadlines, is provided on the programme DLE page: <https://dle.plymouth.ac.uk/course/view.php?id=38727>

You should note that there are rare occasions where this assessment programme might need to be revised. If such a revision occurs then you will be informed in good time and told what the changes are.

Comprehensive information about the University’s assessment regulations can be found here: <https://www.plymouth.ac.uk/student-life/your-studies/essential-information/regulations>

If you have any further queries see your personal tutor or the appropriate module leader.
