---
title: "Attendance"
---

We expect you to attend all scheduled classes and other events that are part of 
your programme of study. All teaching is developed to give you relevant, necessary experience. We know that students who do not attend perform less well. Regular attendance is also a condition of a student loan. You should therefore be in attendance throughout the teaching and assessment periods.

You also need to ensure that you are available during the referred assessment period (see "Academic Year") in case you have any referred examinations or coursework.

If there are unavoidable circumstances which mean that you cannot attend the University then you can register these circumstances through the Faculty of Health (see the section on Extenuating Circumstances). You should also discuss these circumstances with your personal tutor.

### Attendance monitoring

Attendance at scheduled sessions is monitored via the use of check-in codes that are provided by the member of staff leading the session. Students should enter these via the University app to record their attendance. Although there are no check-in codes for ad-hoc sessions (e.g. meetings with your tutor or dissertation supervisor), staff enter attendance data for these meetings into the same system so that we maintain an overall picture of your engagement.

### International students

If you are an international student, please be aware that lack of attendance may lead to exclusion or failure to obtain the qualification that you are seeking. 

The University records information about student engagement and attendance. We expect students to engage honestly with this, and may take disciplinary action against any student who attempts to bypass systems or 
provide false information regarding engagement and attendance. 

Information recorded about an individual student’s engagement and attendance will only be acted on at their 
Faculty’s discretion and as per academic regulations, unless there is a concern for the student’s health or 
wellbeing, or the student holds a Tier 4 visa. Please see separate information regarding the University’s 
responsibility to monitor the engagement of Tier 4 students, and actions that are taken if a Tier 4 student is not attending or engaging with their course satisfactorily. Information for Tier 4 students can be found here: 
[Information for Tier 4 students](https://www.plymouth.ac.uk/international/compliance/current-student).