---
title: "Cancellations"
---

If a class has to be cancelled, we will endeavour to get that information to you as early as possible (usually via the module website and email). However, sometimes lecturers become unavailable (e.g. sudden illness) without much notice. When this happens, please use your own contact networks to share the information with other students who may not have checked their email. To avoid cancelling classes wherever possible, we may change the order of classes at short notice. Again, we will communicate this to you as early as possible so that you can prepare for the class.

We will try to provide a replacement class for any that is cancelled. If this cannot be arranged, the lecturer teaching the course will rearrange teaching so that all essential material is covered. This may require topics to be integrated into different lectures and taught in a slightly different manner than was originally intended. The lecture slides, readings, and any additional notes for the cancelled class will still be made available so that students can cover the topic as it would have been in class. 

