---
title: "Careers Resources"
---

Great careers aren't built overnight. They evolve out of lots of small efforts, undertaken daily, that eventually grow into the seeds of a satisfying career. Taking the initiative and planning your career means you are more likely to get the type of job that you will enjoy.

For Psychology students there are numerous great sources of information available.

### British Psychological Society

This site will tell you all about careers in psychology, and courses and qualifications that will help you get the career you want.

<http://www.bps.org.uk/careers-education-training/careers-education-and-training>

### Careers Service

The University has great careers information for all students. This service can be accessed through the student portal and university web pages: <http://www.plymouth.ac.uk/services/careers>

### School careers resources

Talks by professional psychologists and those in careers related to psychology will take place throughout the academic year and are open to all psychology students. Details will be emailed and posted on the careers notice boards nearer the time.

### Advice

It may be time-consuming to follow up all these sources of information, but they will be valuable in terms of what you learn about the world of work and how you can pursue the career which you want.

Perhaps the most important things to remember are these:

1.  When you apply for particular vacancies, it is worth taking care over the application to ensure that you create the best possible impression.

2.  The process of applying for vacancies commits you to absolutely nothing. Often the selection process proves an invaluable source of new occupational information (especially if you get an interview) as well as a chance to improve your job-seeking skills.

3.  The majority of students cope with the transition from higher education to graduate life without any major difficulty. This is often because even if they leave job seeking until after exams, they have taken the time and trouble to gather information about themselves and their future gradually during their final stage. Thus, in considering your future career, the best way to be is relaxed but purposeful.
