---
title: "Contacting Staff"
---

There are lots of members of staff in the School who can help you during your time with us, and we are very happy to do so. However, please try to use our time efficiently. There are several sources of information you can use which might answer your question more quickly. Check the module and [programme](https://dle.plymouth.ac.uk/course/view.php?id=38727) pages on the DLE, this handbook, the [Student Handbook](https://www.plymouth.ac.uk/your-university/governance/student-handbook), and the range of learning resources in the library. If you have checked all relevant sources and your question is still not answered then we'll be happy to help.

### Office hours

Our academic staff are based in Portland Square on the second floor of A block and B block. There is a map showing staff offices [here](https://bit.ly/3kzyvMa).

Staff typically specify two 'office hours' during the week when they are available for student queries. Please use these office hours. Talking to us face-to-face is usually a friendlier and more efficient way of communicating than email, and students who come to our office hours tend to have a better experience.

To use our office hours, please book a slot so we know you're coming and can make sure we are there. You can see details of each staff member's hours, where their office is, and book a slot here: <https://dle.plymouth.ac.uk/course/view.php?id=66067>

Many staff will be available to see you outside their office hours, but please make an appointment first via email. All our staff are researchers and administrators as well as teachers, so please don't be offended if you drop by unannounced and we are busy.

### Email

You can get in touch with us via email, but please come to our office hours if you can. Most staff get far too much email, and it's much nicer talking to people in person.

If you do get in touch with us via email, we should reply within two working days. If you don't get a reply (e.g. because the person you emailed is ill) you can contact somebody else, using the table below as a guide.

Email addresses for most staff can be found [here](https://www.plymouth.ac.uk/schools/psychology/academics). Alternatively, you can search for us on Google - searching for "jeremy goslin plymouth university" gives me Jeremy's University page, which contains his contact details.

### Who to contact

This is a general guide giving some examples of queries you might have and who could answer them. You should consider this in conjunction with the previous page, "Other Staff".

| Query                                                            | Contact                                                                                                                                                                                                                                                                                                 |
|------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Personal/medical circumstance affecting study                    | Personal tutor. If you can't contact them, try the Senior Tutor. You may also want to apply for extenuating circumstances.                                                                                                                                                                              |
| Unsure about course - thinking about changing or withdrawing     | Personal tutor. To withdraw, you would need to contact the Programme Lead and complete some paperwork provided by the Faculty.                                                                                                                                                                          |
| Query about a module, e.g. details of the teaching or assessment | Module lead, or the member of staff who teaches the specific part of the module you want to discuss. If you don't get a satisfactory response, contact the Associate Head of School for Teaching and Learning, or the Programme Lead.                                                                   |
| Query about computing or other technical matters                 | The Technical Office in the Link Building, or the Student Hub in the library.                                                                                                                                                                                                                           |
| Disappointed with a mark                                         | The module lead or the person who set the assessment. They won't be able to change your mark, but they can give you additional feedback.                                                                                                                                                                |
| Disappointed with the programme                                  | You could contact the staff concerned, or your student reps. They will raise the issue at the Undergraduate Programme Committee. If needed, try the AHoS T&L or the Programme Lead. Please also see the page on [course feedback](https://plymouthpsychology.github.io/handbooks/course_feedback.html). |
| Need a reference, e.g. for a job                                 | Personal tutor, or another member of staff who knows you well. Students in Stage 4 or above often ask their dissertation supervisors as they have experience of working together.                                                                                                                       |
| Want to appeal your results                                      | See [the University's page for appeals and complaints](https://www.plymouth.ac.uk/student-life/your-studies/essential-information/complaints-appeals).                                                                                                                                                  |
| Want to make a complaint                                         | As above.                                                                                                                                                                                                                                                                                               |

### Other contacts

School office: PSQ B223, [office.psy\@plymouth.ac.uk](mailto:office.psy@plymouth.ac.uk){.email}, 01752 584800

Technical office: Link 305, [tech.psy\@plymouth.ac.uk](mailto:tech.psy@plymouth.ac.uk){.email}, 01752 584853

Faculty office: Rolle (4th floor), [k.barnett\@plymouth.ac.uk](mailto:k.barnett@plymouth.ac.uk){.email}, 01752 585332 or 01752 586999
