---
title: "Course Feedback"
---

At various points whilst studying on your programme, you will be asked to provide formal structured feedback about the modules you are studying and the programme as a whole. 

This feedback takes two forms. First, you will be asked to complete a module evaluation for each module. These evaluations are online and are completed by accessing a module evaluation web page. You will be given instructions on how to access the page at the time when module evaluations are required.

Second, the University asks students in Stages 1 and 2 to complete an annual University-wide survey called the Student Perception Questionnaire. This allows the University to track the views of students about their course and the University facilities. Students in Stage 4 complete a National Student Survey. The results of this survey are made known nationally and contribute to the overall profile of the University.

When you are asked to complete one of these evaluations, please take the time to do so. The information which can be obtained from them is vitally important in monitoring the quality of courses, and provides information which can help in the planning of future courses and facilities.

All responses to these evaluation instruments are confidential or anonymous. You will never be identified as an individual. There will be no comeback on you in any form for any views which you express in these surveys.

### Anonymous feedback box

We also have an online feedback box, which you can use to tell us about the course. It is completely anonymous. It is also a quick way of providing feedback - unlike the module evaluations that take place when each module finishes, comments in the online feedback box can be made at any time and will be sent to the Programme Lead instantly. 

Your identity is not recorded unless you write your name or email address in the box, so you might prefer this to email if you want to express your views without us knowing who you are. If you want a reply, make sure you include your name or email address at the end of the comment. 

The feedback box is here: <https://www.psy.plymouth.ac.uk/communitybox>

