---
title: "Coursework Format"
---

All coursework should be written using the coursework template provided on the relevant module DLE page. This has the correct margins, font, line spacing and so on pre-set. However, these requirements are also set out below.

When submitting written coursework, you must use the following style guidelines unless the module leader instructs otherwise:

* Use Arial 12 point font
* Use double line spacing
* Use left justification
* The top and bottom margins should be 2.5 cm. The left margin should be 1 cm and the right margin should be 4 cm.  The extra space in the right margin is to allow for written feedback.
* Put your student number on each page (in the Header). Do not put your name on the pages
* Make sure the piece of work is referenced according to APA guidelines. Unless other instructions are explicitly given by the module leader, you should fully reference each piece of coursework. However, the reference list does not contribute to the page count for the assessment
* Include diagrams and figures within the body of the assessment rather than on separate pages as appendices. Label each diagram, figure, or table with a clear and brief title.

### Page limits

The module leader will normally stipulate a maximum number of pages using the School’s style guidelines. You must follow the style guidelines above in order to conform to the stipulated number of pages for the assessment. If you exceed this page length or you do not follow the style guidelines then your work will be penalised by the deduction of grades.

The specified page limit excludes the reference list.

The deductions for exceeding the page limit will be applied as follows:

* Up to 1 page over = 1 grade reduction
* Up to 2 pages over = 2 grade reduction
* Up to 3 pages over = 3 grade reduction
* More than 3 pages over = 4 grade reduction

A one-grade reduction means, for example, that the work would receive a B- instead of a B. A four-grade reduction would mean that you receive a C- instead of a B. 

There will also be grade deductions if you submit work which does not conform to the style guidelines. Deductions will be made according to the extent of deviation from the style guidelines and the overall length of the submitted assessment.


