---
title: "Coursework Returns"
---

Work submitted electronically will normally be returned either as email attachments or to be downloaded from a location that you will be notified of (e.g. the DLE).

Work will normally be returned twenty working days after the submission date. If there is an unavoidable delay (e.g. due to staff sickness) you should receive an email from the module leader giving the revised return date. If the specified return date has passed and your work has not been returned, please contact the module leader in the first instance to check what is happening to the assessment.

### Written feedback

It is very important to us that we provide you with constructive and helpful feedback that helps you to understand what you can do to improve your future work and develop your skills. That is why we provide many different ways for students to get feedback on their work.

Written coursework is normally marked using Turnitin's Feedback Studio. To access your feedback, you should click on the Turnitin icon next to your submission. There is more detail on how to use Feedback Studio on the [programme DLE page](https://dle.plymouth.ac.uk/mod/page/view.php?id=1673875) in the "Assessment" section.

You should get annotations on your work, e.g. using text comments and stamps. There will also normally be feedback on the front of your work that summarises and contextualises the later comments.

In some instances, you will also receive:

-   Generic feedback, provided to the whole cohort, describing things that differentiated strong and weak essays, reports, and exams
-   Verbal feedback in tutorials, tutor meetings, placement interviews, and follow-up meetings with module leaders or staff who set assessments

Furthermore, staff are available to clarify feedback. If you are unsure what a comment means, please come and ask us. The first person to approach is the lecturer who set the question. They are the person who can best clarify feedback for you. The module leader can help you too. You should do this by booking an appointment to see us during our office hours - each member of staff has a scheduler [here](https://dle.plymouth.ac.uk/course/view.php?id=66067).

Remember: There are many ways you get feedback. Being proactive and talking to staff is an important part of the feedback process.
