---
title: "Degree Awards"
---

The following summarises the main criteria for awarding and classifying degrees. It is a guide only. The full regulations for the award of degrees and intermediate awards can be found in the [Student Handbook](https://www.plymouth.ac.uk/your-university/governance/student-handbook).

To be awarded an honours degree you should have passed 360 credits of which at least 120 are at level 6 (studied in Stage 3 or 4) and a further 120 at level 5 (Stage 2). For BSc Psychology (and combined honours programmes) all modules are 20 credits except the final year project module, PSYC605 (40 credits).

For the classification of a degree, Stage 4 is weighted more highly than Stage 2, which in turn is weighted more highly than Stage 1. For the BSc, Stage 4 is weighted at 0.6 (60%), Stage 2 is weighted at 0.3 (30%), and Stage 1 is weighted at 0.1 (10%, calculated from the best 80 credits).

At each stage of the degree, your modules give you an average percentage for that stage. Your overall percentage is calculated as:

(0.6 x Stage 4 average) + (0.3 x Stage 2 average) + (0.1 x Stage 1 average, best 80 credits only)

Your degree classification is based on the overall mark you have achieved, using this method.

To determine your degree classification, your overall mark is rounded to the nearest whole percentage point. The precise boundaries are therefore as follows:

69.5% plus: 1st class award

59.5 to 69.49%: 2i class award

49.5 to 59.49%: 2ii class award

39.5 to 49.49%: 3rd class award

However, there are alternative classification methods which are used if you fall just below the criteria in terms of percentage. The cut off for consideration is a percentage within 3% of the award boundary (e.g. 47%, 57% or 67%). If this is the case then we may award the higher class of degree according to either of the following two methods. These methods can only result in the award of a higher degree class (never lower), so they can only work in your favour.

#### 1. Stage 4 average

If your Stage-4 average is within the higher award range you can be awarded this higher class of degree. For example, if your overall average is 58% but your Stage-4 average is 61%, you can be awarded a 2i class degree.

#### 2. Overall profile

We may award a higher classification based on overall profile. This means that students who usually achieve module marks in the higher class may be awarded that class of degree, even if their overall average is below the threshold. This is rare, but sometimes applies to a student who has a small number of credits with much lower marks that drag down their overall average.

The calculation is somewhat complicated, but the principle is that we look at how many credits fall into each degree class across Stage 2 and Stage 4. We weight Stage 4 twice as much, by effectively doubling the number of Stage 4 credits in the higher class. We then look to see whether the majority of credits are in the higher class (or better), and award the higher degree if they are.

For example, consider the following example profile for a student with an overall average between 57% and 59.49%:

Stage 2: 40 credits below 2i, 80 credits at 2i or higher\
Stage 4: 60 credits below 2i, 60 credits at 2i or higher

This student has the majority of their credits at 2i or higher, so we could award that higher degree class.

Also consider the following case for a student with the same average:

Stage 2: 80 credits below 2i, 40 credits at 2i or higher\
Stage 4: 40 credits below 2i, 80 credits at 2i or higher

This student has exactly half their credits at 2i or higher based on a simple count, but because we weight Stage 4 more heavily we could award the higher degree class. Note that if we swapped the Stage 2 and 4 profiles then we would not award the higher degree.
