---
title: "Exams"
---

Exams are an important way by which we assess students' academic achievement. All examinations require you to answer questions in a limited time. The time limit for in-person exams is usually 2 hours. Details about the exam structure for each module will be provided on the module DLE page and the module outline. For further information about particular exams you should contact the relevant module leader who will be able to advise you.

Because the questions are unseen, and there is a limited time in which to answer the questions, exams are notorious for producing stress and anxiety. However you can minimise this stress by planning for exams. You can do this by:

· Familiarising yourself with practice exam questions, including those set as coursework

· Knowing the whole curriculum on which the exam will be based

· Planning your time in an examination

· Practising writing examination answers under exam conditions

· Starting revision in good time

General criteria for marking written work are provided in this handbook. These apply to longer exam answers as well as coursework. For shorter exam answers, the marking criteria should be obvious. For example, if you are asked a simple question with one mark allocated for the answer, you will be awarded the mark if you answer correctly.

You can also get help on developing your examination technique through the University's Learning Development service (www.plymouth.ac.uk/learn) who run short courses designed to help students to gain more confidence with their academic techniques.

### Exam FAQs

Below is a list of Frequently Asked Questions (FAQs) about exams.

Q: Will material taught in Semester 1 appear in the exams in Semester 2?

A: No. Modules run only in one semester. Each module is examined in the examination weeks within the semester in which it was taught.

Q: How many questions will there be in the exam paper, and how much choice of question will I have?

A: This will vary by module, and each module can use a range of question types. Module leaders will provide guidance about their exams.

Q: Will there be a question about 'topic x' in the exam? 
A: We do not give you this information because it encourages 'question-spotting'. Please do not approach staff with questions that seek to elicit information about exams that could lead to question-spotting.

Q: What material do I have to learn to pass the exam? 

A: An exam can contain questions on material covered in lectures, provided in handouts, or covered in required reading or Psylab.

Q: Should I include citations in an exam answer? 

A: Yes, if you can and it's appropriate. As with written coursework, you should aim to use citations to support your argument. However, don't leave something out just because you can't remember the citation. Markers know that you are bound to forget some details, and using the correct citation is less important than the content of what you write.

Q:  I failed exam X, or coursework Y, by Z%. Will I fail my module or even stage? 

A: Your personal tutor can give you advice on the interpretation of the current exam regulations and the options in the event of failure or other outcomes. However, your tutor cannot tell you if you have passed or failed examinations, or if you will be able to progress to the next stage of your degree. These decisions are taken by the Award Assessment Board which meets to make decisions on degree awards and progression in June of each academic year. The decision of the Board and the options available to you will be communicated to you by letter. You can then seek further advice on the best course of action by approaching your personal tutor.

Q: How long does my exam last? 

A: Exams normally last two hours. Confirmed information is included on the examination timetable published by the University.

Q: When and where does my exam take place? 

A: This information is included on the examination timetable published by the University.

Q: I have applied for and received valid extenuating circumstances for the period of the exams. Should I attempt to take the exams or just miss them? 

A: Extenuating circumstances will only cover you for missing an exam. If you decide to sit an exam, the mark will stand even if you do not do as well as you know you could. However, students should be be aware that if you fail more than 60 credits then you would normally have to repeat the failed modules in the following year rather than being able to take referred exams in August. This applies even if you have valid extenuating circumstances for missing assessments.

Q: I missed a lecture. Where do I get the information I missed? 

A: Staff always put resources and other information related to their teaching on the relevant DLE page for the module. This material can include: the module outline, a list of lectures, handouts, learning support materials, readings and notes for the session(s). You may also be able to watch the lecture using Panopto, our lecture capture system. However, we cannot guarantee that all lectures will be available on Panopto (e.g. in the case of a technical fault).

Q: How much does the exam/coursework contribute to the module mark? 

A: This information should be included in the module outline. It will also be provided on the course DLE page.

Q: Where do I get a module outline? 

A: The outline for every module is on the DLE.

Q: Where do I get help in writing examination essays? 

A: Talk to your personal tutor. Also you can get information from the Learning Development Service who offer a range of Study Guides.
