---
title: "Extenuating Circumstances"
---

There might be occasions when you are unable to complete an assessment because of circumstances that are out of your control, e.g. illness. We call these 'extenuating circumstances', and the University has procedures for ensuring that you are not disadvantaged.

Extenuating circumstances are not simply any circumstances that affect your ability to complete an assessment. They will only be deemed valid if they are exceptional, outside your control, and occurred during or shortly before the assessment.

The University's procedures are outlined here, along with examples of valid extenuating circumstances:

<https://liveplymouthac.sharepoint.com/sites/x70/SitePages/Extenuating-circumstances.aspx>

The application form for extenuating circumstances is available at the above page, together with a detailed policy document.

### Long-term health conditions

Long term health conditions can be described as conditions which:

-   are persistent, typically lasting for more than three months and often life-long

-   cannot be resolved in a short time, or which will recur regardless of action, or which need to be managed on a long-term basis

-   are a long-term or permanent illness that often results in some type of disability and which may require you to seek help with various activities

-   can be managed but can 'flare-up'

Examples of conditions which fall into this category are: Cystic Fibrosis, Costochondritis, Fibromyalgia, Chronic Fatigue Syndrome (ME), Psychosis, and Bipolar Disorder.

If you have a long-term health condition, you should discuss any support needs with Disability Services (or equivalent in partner institutions) before or soon after commencing your programme of study. It is hoped that the condition can be managed and / or you can be supported sufficiently by Disability Services (or its equivalent in partner institutions).

<https://www.plymouth.ac.uk/student-life/your-studies/essential-information/exams/exam-rules-and-regulations/extenuating-circumstances>

However, there may be times when unexpected difficulties or flare-ups arise. On these occasions you are required to claim extenuating circumstances affecting specific assessments. However, you may wish to obtain a long-term ill health declaration that means you do not have to submit evidence for each extenuating circumstances claim.

To do this, you must complete a form that is available from the Faculty Office (or equivalent for partner institutions). This form must be accompanied by a statement from your GP, hospital consultant or appropriate specialist responsible for your treatment which provides clear confirmation of the nature, severity, duration and effect of your condition on your studies. You should submit the form to the Faculty Office for consideration.

Once a claim is authorised, you will continue to be required to submit an extenuating circumstances claim for any missed assignment submission deadline, test, or examination which is directly attributable to a flare-up of your long-term health condition, but you will not be required to resubmit evidence.

As a result of this process, we may need to invoke the Fitness to Study process to consider your case in more detail.

You must inform your Faculty or partner institution of any change in your condition, whether improvement or deterioration, in order that the claim can be reassessed. The Faculty or partner institution may require further evidence from time to time. You will be contacted at the start of each academic year to review your case.

### Study and Wellbeing Policy

The University is committed to an ethos of equality and inclusivity, and aims to facilitate and promote positive health and wellbeing through the recognition and understanding of all relevant health conditions and disabilities. Occasionally a student's circumstances or health may impact upon their own, or others' ability to fulfil that potential. Levels of risk will be assessed by the University on a case-by case basis in conjunction with appropriate professionals.

The Study and Wellbeing Policy and the accompanying procedures are to be followed by University of Plymouth staff where significant concerns have arisen as a result of a student's extended absence, health condition, wellbeing or other circumstances that lead to an inability to progress in their programme, or that adversely affect others. The key purpose of the policy is to ensure that the best interests of the student are met and to provide appropriate guidance and support. Further details can be found in this link:

<https://www.plymouth.ac.uk/student-life/your-studies/essential-information/regulations>
