---
title: "Failing Modules"
---

There are occasions when at the end of the year students may have failed one or more of their modules. Failure can occur because of non-attendance at exams, late or non-submission of coursework, or poor performance in the required assessments for a module. 

A module can also be failed due to failing a pass/fail requirement even though the coursework and/or exams have been satisfactorily completed. 

Students may have extenuating circumstances for particular assessments which have been deemed valid and which account either completely or in part for the failure.

Students will be officially informed which modules they have failed through their end of year transcript. 
The award assessment board can make a number of decisions in relation to such failures. The Board has ultimate discretion in its decisions so the following points are provided as guidance only.

•	If a student has failed modules totalling up to 60 credits (e.g. 3 x 20 credit modules), then they would normally be required to resit the relevant assessments prior to the start of the next academic year before they will be allowed to progress to the next stage or be awarded a degree. The overall mark in the module in which the student is ‘referred’ will be capped at 40%. This mark will be carried forward and used to determine the overall mark for that stage of the degree. Students are allowed a maximum of two attempts at passing a module.

•	If a student has failed more than 60 credits then they would normally be required to repeat the failed modules in the following academic year. Again, the overall mark in the module in which the student is referred will be capped at 40%. Students are allowed a maximum of two attempts at passing a module. 

•	The Board can also decide whether a resit or a repeat is as a first or second attempt. If a resit is a second attempt then the overall module mark is capped at 40%. However, where the board has decided that a resit is a first attempt then the student will resit the assessment as if for the first time, and the mark obtained will not be capped at 40%. The decision to allow a resit as a first attempt normally only occurs where a student has valid extenuating circumstances relating to the particular assessment. It is important to note that valid extenuating circumstances never alter marks. Extenuating circumstances only allow the student to resit or repeat the assessment as the same attempt. In the case of coursework, students with valid extenuating circumstances may be allowed to submit the assessment after the deadline but within a specified period. Students with valid extenuating circumstances will be informed via email of the decision relating to their assessments by the Faculty Extenuating Circumstances Committee.
