---
title: "Introduction"
---

In Stage 4 of your programme you are free to chart your own path across 27 specialist psychology options. This offers you more than 7,000 unique pathways so you can follow your aspirations and gain specialist skills and knowledge for **your** future.

Our Stage 4 options are delivered in four modules, listed here. Students taking BSc Psychology or any MPsych course take all four modules, and students studying a combined honours degree (BSc Psychology with another subject) take the modules marked \* only.

#### Semester 1

PSYC611: The Psychology of Emotion\*

PSYC612: Current Topics in Psychology 1

#### Semester 2

PSYC613: Psychology in Practice\*

PSYC614: Current Topics in Psychology 2

### Course structure

Option modules contain a number of option topics that students choose from. This means that students can choose different options, even though they may be registered for the same modules.

The structure of each module is described briefly here. More details of each module are available via the menu.

PSYC611 starts with two weeks of core lectures on the psychology of emotion, followed by a set of options that run in parallel for four weeks. You will choose one of these options. Each option takes a different approach to the topic of emotion, and uses different research methods. This is intended to give you a chance to refresh your research skills in preparation for your dissertation.

PSYC612 consists of two blocks of options, which run one after the other for three weeks each. Students must choose one option from each of Block A and Block B.

PSYC613 consists of a set of options with an applied focus. Each runs for six weeks from the start of Semester 2. You will choose one of these options.

PSYC614 has the same structure as PSYC612 above: Two blocks of options, which run one after the other for three weeks each. Students must choose one option from each of Block A and Block B.

Across the year, single honours students should choose six options: one from PSYC611, two from PSYC612, one from PSYC613, and two from PSYC614. Combined honours students should choose one option from each of PSYC611 and PSYC613.

| Weeks                    | Block     | Students       |
|--------------------------|-----------|----------------|
| Semester 1 weeks 1 - 6   | PSYC611   | All            |
| Semester 1 weeks 7 - 9   | PSYC612 A | Single honours |
| Semester 1 weeks 10 - 12 | PSYC612 B | Single honours |
| Semester 2 weeks 1 - 6   | PSYC613   | All            |
| Semester 2 weeks 7 - 9   | PSYC614 A | Single honours |
| Semester 2 weeks 10 - 12 | PSYC614 B | Single honours |
