---
title: "Lecture Etiquette"
---

One of the most common complaints made to members of staff by students concerns noise and other disturbances in lectures or other taught sessions. This noise mostly arises from students talking persistently during the lecture or using their phones. Talking, texting, listening to music through headphones, packing up before the lecture has finished, and so on are all distracting to fellow students and staff alike.

These activities are not only inconsiderate and rude, they place fellow students in a position where they are unable to engage fully with the content. This is especially the case for those students who have a hearing impairment or other special educational need. In the case of such students, the University has statutory obligations under the Equality Act 2010 to take reasonable steps to ensure that the learning environment is appropriate for disabled students.

While a lecture is in progress it is essential that people remain quiet and attentive. Please do not talk to others during the lecture in a way that is likely to be disruptive. It's also important that you don't use phones and laptops in a way that distracts others. 

Please also note that you should not leave the lecture room until the lecturer has signalled the end of the lecture. If you arrive late to a lecture, please enter by the back and take a seat as quietly as possible.

These are all obvious rules to follow. The University considers disruption of lectures to be a disciplinary offence. To that end, lecturers can ask anyone seen disrupting lectures to leave. If the problem persists then the School will take steps to identify individual offenders and initiate disciplinary proceedings against them.
