---
title: "Lecture Recordings"
---

The University expects all students to participate fully in the learning opportunities offered by their programme of study and encourages all students to take advantage of additional opportunities for development, both personally and academically. As part of this, attendance at lectures is an expectation. We also believe that note-taking is itself a valuable skill, and research suggests that it enhances retention of information.

However, we also recognise that it can be useful to review lectures later. For this reason, lectures are recorded using a lecture capture system called Panopto. This records audio, video, and slides. Links to view lectures will appear on the relevant module page of the DLE, usually within 24 hours of the lecture taking place.

### Personal recordings

There are occasions when Panopto fails to record a lecture, although these are rare. If it is critical for you that you have a recording, then you can make your own recording of a lecture. However, you must seek the permission of the lecturer before the lecture begins. Lectures and learning materials are the intellectual property of the University and the staff who develop them. Any recording that is made with the lecturer's permission must not be distributed in any format (including through posting the recording or a transcription on the internet e.g. Facebook, YouTube etc.). The information may only be used in support of your own learning or other students registered on the programme. Unauthorised sharing of lectures may be dealt with under the Code of Conduct and Disciplinary Procedure for students.

The University recognises that recording can form a reasonable adjustment for students with disabilities. If you wish to record lectures or other learning opportunities in order to make the information more accessible to you due to a disability, please contact [Disability Services](https://www.plymouth.ac.uk/services/impairments-health-conditions-and-disability) for advice on ways the University can support you. If Disability Services have notified your school that recording lectures will support your learning, you will not need to seek the permission of the lecturer before the lecture begins, but recordings must not be distributed in any format.
