---
title: "Library"
---

The Library houses a comprehensive range of books, journals and DVDs, networked PCs, media workshop facilities and a variety of study spaces. The Library is open 24/7.

Most of the psychology collection is located on Level 2 of the library. [PRIMO](https://primo.plymouth.ac.uk/), the library search system, will give you the exact shelfmark for any book or journal you are looking for as well as access to a range of electronic information sources.

Staff at the Information Desk in the library can help with queries about accessing resources.

More detailed information about library services and facilities can be found by going to the library pages via the Student Portal, or the [Library page on the University Website](https://www.plymouth.ac.uk/services/library-services).

Special support services are available for students with disabilities and part-time and placement students. Please ask library staff for more details.

Although the Library holds a large collection of psychology books and journals, both print and electronic, there is great demand for some texts. To alleviate pressure, some books are placed on reference use only in the Library and many books and journals are available electronically via PRIMO. However, there will be occasions when demand outstrips supply of major texts. The best way to avoid this problem is by reading diligently throughout the year and not simply when you have an essay to write or an exam to sit! In order to help in this, psychology lecturers will provide, wherever possible, a list of key readings some time ahead of when you need them. This means you will be able to access them well ahead of time. Do not wait until the last minute, otherwise demand may be such that you experience difficulty in getting hold of what you want. If you are finding it hard to access particular items, please contact the relevant module staff.
