---
title: "Marking Criteria"
---

Awarding marks to written coursework, exam answers, and other assignments at degree level seldom involves the mechanistic application of fixed marking criteria. In recognition of this, markers will seek evidence for the presence of a number of strengths and weaknesses. Our generic marking criteria are [here](https://dle.plymouth.ac.uk/mod/resource/view.php?id=1651700).

This table contains example strengths and weaknesses corresponding to different classes and grades of mark. These examples are not an exhaustive list of the very many things considered in marking a complex piece of written work. They are included here as a general guide to what typically distinguishes strong from weaker work.

For coursework, you will be given marking criteria for each assignment. These will usually be included as part of the coursework template that you will use to prepare your submission. They may be the same as the generic criteria, or they may include additional criteria that address other aspects of the assignment.

In applying marking criteria to specific pieces of work, markers will first assess whether the strengths and weaknesses associated with a particular degree class are present in the answer, and to what degree. To qualify for a given degree class, an answer should display all or most of the strengths for that class and lower classes. It may also be subject to one or two of the weaknesses associated with that class, but should largely be free of the more serious weaknesses associated with lower classes.

Markers may decide that certain strengths are sufficient to compensate for specific weaknesses, and select a degree class accordingly. For example, an essay which answers the question, is generally accurate, well-informed, and well-organised, but which contains some inaccuracies, omissions, and flaws in the argument, may still merit an upper-second class mark.

Additionally, markers may decide that specific strengths are present to such a degree that they compensate for the absence of one or a few other strengths associated with a particular degree class. For example, a highly original, insightful and well-argued examination answer may merit the award of a first class mark even though it contains some omissions or minor inaccuracies.

Equally, specific weaknesses may be present that are judged so serious that strengths associated with a higher degree class are insufficient to provide compensation. For example, a reasonably comprehensive, well-organised and well-presented essay may merit a lower-second class mark - or even a third-class mark - if certain concepts or facts essential for an adequate answer to the question are misunderstood or omitted.

Markers will also take account of the time students have available to answer questions in an exam, and will expect evidence for a greater depth of analysis and a more extensive knowledge base for longer written assignments and examination answers, than for shorter examination answers and written assignments.

It is important to note that marking a complex piece of work, such as an essay, is a holistic process, taking into account very many specific elements, but most importantly the degree to which a piece of work succeeds as a whole. It is the overall impression of the marker that is reflected in the final grade.
