---
title: "MPsych Transfer"
---

The school offers three MPsych programmes, which are 'integrated Masters' degrees. This allows students to study for an additional year (Stage 5) that includes Masters-level modules. It is possible for students studying one of our BSc programmes to transfer to an MPsych, and details are provided on this page.

The MPsych is still an undergraduate degree, and not the same as an MSc degree, but it prepares you for a more advanced and specialised career in psychology.

Students enrolled on an MPsych take exactly the same Stage 1, 2 and 4 modules (including final year project) as those enrolled on BSc Psychology. However, instead of graduating after Stage 4, MPsych students take the extra Stage 5 year with the Master's level modules, and graduate the following year with an MPsych degree (instead of a BSc degree). Stage 5 consists of 120 credits, including a 40 or 60 credit research project.

Our MPsych programmes are accredited with the BPS, and students enrolled on an MPsych degree should be able to obtain student loans for tuition fees for the whole 4 years (or 5 years including a placement year).

An alternative route is to graduate with the BSc and then take a traditional MSc course. We currently offer three MSc programmes that correspond roughly to the three MPsych programmes: MSc Research Methods in Psychology, MSc Clinical Psychology, and MSc Human Neuroscience. Students taking an MSc will normally already have a BSc, and will take 180 credits (again including a 40 or 60 credit research project). Because it requires more credits, studying for the MSc is more intensive than the MPsych, but the content covered in both MPsych and MSc is otherwise equivalent.

It is possible to transfer or change enrolment to the MPsych from the BSc degree, as follows:

### Transfer from Stage 1 of BSc

Students who have just started the BSc degree have a limited opportunity from induction week up to the end of the first week of teaching in Semester 1 to change enrolment to the MPsych Stage 1. Please contact Karen Barnett for more details of Stage 1 transfers: <k.barnett@plymouth.ac.uk>

### Transfer from Stage 2 or 4 of BSc

Stage 2 and 4 students can request to transfer to MPsych provided they have attained a minimum average grade of 50% at the end of the academic year. The request to transfer can be made any time before the end of the year. Transfers will be provisional until the end of Stage 4, at which point grades are confirmed and the transfer finalised. Please contact Karen Barnett for more details of Stage 2 or 4 transfers: <k.barnett@plymouth.ac.uk>

### Contacts

If you have queries about either the MSc or MPsych programmes please contact the respective programme leaders:

-   MPsych Psychology, and MSc Research Methods in Psychology: Dr Chris Berry

-   MPsych Psychology with Clinical Psychology, and MSc Clinical Psychology: Dr Alison Bacon

-   MPsych Psychology with Human Neuroscience, and MSc Human Neuroscience: Dr Giorgio Ganis
