---
title: "Options list"
---

This is a list of the options offered in each block in the 2025/26 academic year.

This is a work in progress (updated 09/07/2025) so there is one title tbc and there may still be changes to the running order as we confirm the timetable.

Descriptions of each topic can be found via the menu.

### PSYC601 Block A

1.  Sean Fallon -- Beyond reward: Dopamine and its role in shaping human life

2.  Chris Longmore -- The Human Factor: How do people cause plane crashes and other accidents?

3.  Liam Cross -- Social cognition in action

4.  Charles Or -- Perception of faces

5.  Farid Pazhoohi -- Attractiveness: What, why, and how?

### PSYC601 Block B

6.  Michael Verde -- Memory and false memory

7.  Gray Atherton -- Neurodevelopmental conditions: Theories and practice

8.  Sophie Homer -- Foundations of clinical psychology

### PSYC602 Block A

1.  Chris Berry -- Memory, amnesia, and awareness

2.  Phil Gee and Joanna Newbolt -- Animal behaviour

3.  Gustav Kuhn -- The misdirected mind

4.  Caroline Floccia -- How do children learn to talk?

### PSYC602 Block B

5.  Deanna Gallichan -- Clinical psychology for people with learning disabilities

6.  Giorgio Ganis -- Cognitive and brain basis of deception

7.  Jon Rhodes -- Sports psychology

### PSYC603 Block A

1.  Julie Ji -- Harnessing the human imagination

2.  Matt Hudson -- Social cognitive neuroscience: From evolution to public health

3.  Mila Mileva -- First impressions

4.  Stephen Hall -- Drugs, the brain and behaviour

5.  Jackie Andrade -- tbc

### PSYC603 Block B

6.  Alison Bacon -- Criminals in the making

7.  Chris Mitchell -- Counselling and psychotherapy

8.  Alastair Smith -- The Psychology of Drawing

### PSYC604 Block A

1.  Denis Tatone -- Sociologists in the crib: How infants and children represent social relations, structures, and groups

2.  Clare Walsh -- Mind-wandering and imagination

3.  Andrea Pisauro -- Psychology of AI and mental health in human-robot interaction

4.  Patricia Kanngiesser -- Social norms

### PSYC604 Block B

5.  Kayleigh Wyles -- Psychology and the natural world

6.  Jaysan Charlesford -- Reducing prejudice

7.  Katharine Rimes -- Transdiagnostic processes in mental health problems
