---
title: "Other Staff"
---

Although your personal tutor should usually be your first port of call, there might be times when you need to get in touch with somebody else. This page lists a few examples.

### Senior Tutor

The Senior Tutor is responsible for co-ordinating academic and pastoral aspects of personal tutoring in the undergraduate programmes.

They will also act as a 'reserve' personal tutor if your own tutor is not available, or if you have something to discuss that you would prefer not to raise with your personal tutor.

The current Senior Tutor is Dr Nerissa Ho: [nerissa.ho\@plymouth.ac.uk](mailto:nerissa.ho@plymouth.ac.uk){.email}

### Module Leads

If you have a query that is related to a specific module, it is often best to ask the module lead for that module. They are responsible for the content and assessment of their module, and they are usually the member of staff who will be able to best advise you. The DLE page for each module says who the module lead is, and has their contact details.

You may also want to contact a member of staff who teaches part of a module if your query relates specifically to their teaching.

### Programme Lead

The Programme Lead is the member of staff responsible for the day-to-day running of the programme. They work with the module leads to make sure that all the modules work together as a coherent programme of study. They also chair the Undergraduate Programme Committee, and consider student feedback across the programme. You won't normally need to contact the Programme Lead, but it might be appropriate to do so if you have comments or questions about your course that your Personal Tutor and your student representatives have not been able to resolve.

The current Programme Lead is Dr Peter Jones: [peter.m.jones\@plymouth.ac.uk](mailto:peter.m.jones@plymouth.ac.uk){.email}

### Associate Head of School for Teaching and Learning

The Associate Head of School for Teaching and Learning is a senior member of staff who is ultimately responsible for co-ordinating teaching across all our programmes. You won't normally need to contact them, but it might be appropriate if you have a particularly serious concern or other staff are not available.

The current AHoS T&L is Dr Alyson Norman: [alyson.norman\@plymouth.ac.uk](mailto:alyson.norman@plymouth.ac.uk){.email}
