---
title: "Our Community"
---

One of the great things about being at university is that it means you are part of a community that can provide support with your study and other issues, as well as providing many social opportunities. However, the university community can be quite complex - it consists of your fellow students, staff, Teaching and Research Associates (TARAs) who will support you in workshops, our technical office, the Students' Union, and University services like the library and Student Wellbeing Services.

The purpose of the following pages is to provide you with information about the kinds of support on offer in our community.

### The Student Charter

The Student Charter is an agreement between the University, the Students' Union, and the student body. It sets out the expectations that you should have of the University, and also the expectations we have of you. For instance, you can expect that we will provide you with a challenging and invigorating curriculum, and we expect you to take an active role in your learning.

We hope the charter provides a useful framework for both staff and students. You can find it here: <https://www.plymouth.ac.uk/your-university/student-charter>
