---
title: "Participation Points"
---

As part of the requirements for PSYC424 and PSYC513, you are asked to gain some experience of psychological research through participation in approved studies carried out by project students, research staff, and lecturers. This like a social contract - you are asked to earn points in Stage 1 and Stage 2, and you are later given points to recruit participants when you come to do your dissertation in Stage 4.

Participation is recorded in the form of participation points. You get one point for taking part in a study lasting up to 30 minutes, two points for one lasting up to 1 hour and so on. You will need to collect 22 points by the deadline at the end of the academic year (provided in the deadlines document, on the [programme DLE page](https://dle.plymouth.ac.uk/course/view.php?id=38727)).

Getting the required number of points is part of the module assessment and so if you do not get the required number of points (or pass the alternative essay requirement -- see below) you will be deemed to have failed the module.

You are advised to start collecting points as early as possible and aim to get at least 10 in the first semester. If there is a genuine shortfall in the number of points available then the School may make alternative arrangements to allow you to complete the module satisfactorily.

The School uses an electronic sign-up system for experimental participation. This means that you can select studies and sign up for them on-line. Each experiment will have details of the nature of the experiment, who is conducting it (it could be staff or students), where it is to be held and at what time. You will be sent a reminder electronically shortly before you are due to take part in the study. You should turn up and then participate in the study at the indicated time and place.

If you change your mind about participating, or the experimenter wishes to cancel your appointment, then this is allowed provided that you do so before 16:00 the day before (weekends excluded, so you must cancel a Monday appointment by 4 pm on Friday). If you give less notice, or do not turn up, twice the number of points that you would have got from the study will be deducted from your existing total. If the experimenter fails to turn up, or cancels with less than the required notice, then you are entitled to your points anyway. The electronic system should be able to cope with this, but if there are problems you should contact the points administrator: [sonaadmin.psy\@plymouth.ac.uk](mailto:sonaadmin.psy@plymouth.ac.uk){.email}

If you miss three (not necessarily consecutive) experiments without giving the required notice or with valid extenuating circumstances, you will be locked out of system and must talk to your tutor to explain the situation. The tutor may then email the administrator to reactivate their account. If you then miss three more (i.e. six in total), you will be locked out permanently and must do the alternative essay (see below) instead.

Further details of the electronic system will be given to you at the start of the academic year, and you should also refer to the "Points Manager Participant Guide" available online at <https://www.psy.plymouth.ac.uk>.

The system keeps a record of all experiments in which you have participated and points awarded. This will be automatically used to assess your pass/fail status. If you find any discrepancies in your record which you can see in the system then contact [sonaadmin.psy\@plymouth.ac.uk](mailto:sonaadmin.psy@plymouth.ac.uk){.email}

Details of which studies you participated in are carried forward to allow researchers to recruit participants who have not already done the experiment.

Participating in studies is not compulsory, though it is strongly advised as a valuable experience where you can learn more about the kind of research psychologists carry out. The School considers that experience of being a participant in research is almost essential to running one's own research on others, and to evaluating the psychological research literature. However, if you are unable or unwilling to act as a participant then there is an alternative way to pass PSYC424 and PSYC513: you can write an extended essay on a topic that will be provided at the start of the module. The deadline for submission of the essay will be stated on the DLE page for the module. Also remember that if you fail to collect enough participation points or do not complete the alternative essay on time, then you will fail the module.
