---
title: "Personal Technology"
---

One of the most contentious issues in teaching is how we should manage our use of personal technology such as phones and laptops. Some people have argued that phones should be banned from teaching spaces altogether because they are distracting. Studies suggest that using technology for off-task purposes during lectures can have a negative impact on learning (e.g. [here](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=1595375) and [here](https://www.tandfonline.com/doi/full/10.1080/01443410.2018.1489046)). There is also evidence that your use of technology can harm the learning of other students sitting nearby ([here](https://psycnet.apa.org/record/2013-05913-005)). However, many others believe that students should have the freedom to use their devices as they see fit.

Our position is that personal technology is an essential part of university life, but that we should think carefully about how we use it to support learning, engagement, and community. You will use computers to access teaching materials, analyse data, complete coursework, and so on. Many of you will also use computers to take notes during lectures, so the exclusion of technology from our teaching spaces wouldn't be practical. We also believe that learning to work with technology present is a core skill that all of us need to develop. However, we ask that you consider carefully how you can reduce the tendency of your devices to distract you and others.

Although you will use a laptop for learning, you will rarely need your phone in lectures or workshops. We appreciate that there will always be times when some students need to be able to receive messages about things going on outside lectures, but whenever possible your phone should be out of sight and switched off. You should also make sure that you use your laptops for work purposes only during teaching sessions. Browsing the internet or watching videos during lectures is distracting for the people sitting around you, and is not consistent with our aim of creating an effective and supportive learning environment. 