---
title: "Personal Tutors"
---

A personal tutor is assigned to every student in the School. Your personal tutor is a member of academic staff in the School, so you might also see them in lectures and workshops at some point. This person normally remains as your personal tutor throughout your period of studying psychology at the University.

Personal tutors are responsible for monitoring and supporting you throughout your period of study. If you have an issue which is either personal or academic and which is affecting your performance on the degree, then you should consider your first point of contact to be with your personal tutor.

You should be able to approach your personal tutor if you have any problems. These problems may be academic (e.g. study skills, exam anxiety) or non-academic (e.g. personal difficulties which are affecting your ability to study). You tutor may not have the answers you are looking for, but they should be able to talk to you about the best way forward.

Generally, your personal tutor will advise you on your best course of action given the problem you have. Your personal tutor can advise on what other specialist University services might be able to address your concerns more thoroughly. Otherwise your personal tutor can offer advice and guidance on a range of course related matters, like what to do if you cannot meet a coursework deadline or take an examination, or if you need support for any special needs that may affect your work, or if you feel you need guidance on your academic progress.

Normally, your tutor will be available to see you should you need to see them. It is always a good idea, if possible, to let your personal tutor know what it is you need to see them about beforehand. This allows them time to access any additional information they think that you may find useful. It is important to remember that although your personal tutor may make contact with you from time to time, it is your responsibility to make contact when you need to talk to them. The best way to do this is to book a slot during their [office hours](https://dle.plymouth.ac.uk/course/view.php?id=66067).

### Limits on this support

School staff will normally treat what you tell them as confidential. However, if what you disclose gives cause for concern about your own wellbeing, or the wellbeing of others, they may choose to pass this information on to other parties.

You should also note that tutors are not trained counsellors. The University has access to a professional counselling service and you can be referred to this service should you require it. If you disclose a disability, even in confidence, then your tutor is obliged to advise you to seek advice and support from [Disability Services](https://www.plymouth.ac.uk/services/impairments-health-conditions-and-disability).
