---
title: "Placement Year"
---

Students in the School of Psychology have the option of completing a work placement as part of their degree. Through this route, students take a year out on placement between Stage 2 and Stage 4 of the degree programme. By taking a placement year, students extend their degree to a four-year programme (or five years for MPsych students). On successful completion of the placement, students receive the Certificate of Industrial/Professional Experience as an additional qualification.

Placements provide students with the opportunity to work in a setting where professionals (often professional psychologists) operate and to experience at first hand the sort of work which psychology graduates might undertake. In the past, placements have been undertaken in organisations ranging from clinical psychology services in the NHS, psychology departments in prisons, personnel or human resources departments in large commercial or government organisations, human factors research and evaluation in government agencies, forensic psychology with police training organisations, and research on animal behaviour in zoos and aquaria. All these different organisations represent ones in which psychologists are well established or are becoming so, on a professional basis. Nevertheless, given the ubiquity of psychology in the workplace, just about any type of placement opportunity might be considered!

The aims of the placement year are:

• To experience the ways in which theoretical knowledge in psychology is used and applied in professional work settings.

• To enhance personal development in terms of communication with professionals and users, the ability to apply psychological knowledge and to understand real-life situations in terms of psychological principles.

• To develop generic personal skills relevant to the world of professional work; e.g. communication skills, working as part of a team, taking responsibility for one's own work, being accountable to others.

• To develop an insight into individual vocational needs and gain an understanding of particular career routes in professional psychology.

• To contribute usefully to the work of the placement organisation.

Queries can be addressed to the placements team: [placements\@plymouth.ac.uk](mailto:placements@plymouth.ac.uk){.email}

### Practicalities

Placements normally last 45 weeks with a minimum of 36 weeks and a maximum of 48 weeks. They typically start in late August or early September and run through until June or July of the following year.

Whilst on placement students are still required to pay fees to the University, but at a greatly reduced rate.

Funding of the placement year varies. Some organisations offer a remuneration package consisting of a basic salary in which case the placement student takes on a role similar to that of a full-time employee of the organisation. However, the majority of organisations that offer placements to psychology students do not provide any salary. Consequently, students who undertake placements in these organisations have to support themselves for the placement year. Financial support in these cases usually involves student loans, parental or partner support, or the student's own savings.

It should also be borne in mind that a placement year can involve additional costs not usually incurred as a student, for example, clothing appropriate to the work place and travel costs. Students who are interested in a placement year are therefore advised to establish at an early stage how they would support themselves during a placement year.

Students who are interested in taking a placement are reminded to inform their LEA as early as possible that they are applying for the four year sandwich pathway.

### How to apply

Students who wish to undertake a placement apply during Stage 2. They will subsequently be interviewed (usually in Semester 1 of Stage 2) by their personal tutor or the placement coordinator and an assessment made of their suitability for undertaking a placement. They will then be helped by the placements officer and careers service, to find appropriate placement organisations to which they can apply.

Applying for placements is very much like applying for a job. Students need to make an application to the organisation and they will normally be interviewed by the organisation. The decision to offer a placement rests with the placement organisation and final approval is given by the placements team and HOS.

Many local placement providers take psychology students each year, and the placements team manages a database of opportunities that it advertises to students. It is worth noting too however, that a lot of placements are found by writing speculative letters to relevant organisations (often in a student's home town).

Before a placement is finally confirmed students must have passed all modules in stage 2 of their programme. Furthermore, there are various forms to complete when starting a placement, and the placements team is here to guide you through the process.

### On placement

Whilst on placement students are supported and guided by a placement supervisor and an academic tutor. The placement supervisor is a member of staff at the placement organisation and will often have a professional psychology qualification. This supervisor is responsible for identifying appropriate work for the student and giving feedback and guidance on the performance of his or her work. The academic tutor is a member of staff of the School of Psychology, usually the personal tutor. Contact is maintained throughout the placement between the workplace supervisor, academic tutor, placements team and the student to ensure that the placement is running smoothly.
