---
title: "Prizes"
---

The School awards prizes for academic achievement at the end of each academic year. The decision to award a prize is taken by the Award Assessment Board and their decision is final. You will be informed if you have won a prize.

The prizes are for:

• The student with the best overall mark in Stage 1

• The student with the best overall mark in Stage 2

• The student with the best overall mark in Stage 4

• The BPS prize for the student with the highest overall degree mark

• The prize for the best Stage-4 project in Neuropsychology

• The prize for the best Stage-4 project in Personality and Individual Differences

• The prize for the best Stage-4 project in Qualitative Psychology

• The prize for the best Stage-4 project in Social Psychology

• The Pam Jacobs Memorial prize for the best Stage-4 project in Applied Psychology

• The prize for the best Stage-4 project in Cognitive Psychology

The Faculty of Health also sends commendation letters to those who achieve an aggregate of 70% or higher in any stage of the programme, and to those awarded a first class honours degree.
