---
title: "Programme Structure"
---

Your undergraduate programme consists of several stages, or years of study.

Stages 1 and 2 correspond to the first and second years, and Stage 4 corresponds to the final year.

Stage 3 is an optional placement year, undertaken by around a quarter of our students. Information on Stage 3 is provided in the [Placements](https://plymouthpsychology.github.io/handbooks/placement_year.html) section of this guide.

Students taking an MPsych programme have an additional year of study, Stage 5.

### Modules

Each year of study is made up of a number of modules, listed on the following pages. A module is a self-contained unit of study containing teaching and assessment. In order to progress from one stage of your programme to the next, you need to pass each of the modules in that stage. For example, to pass Stage 1 and progress to Stage 2 you must pass all six Stage 1 modules.

Each module has a DLE page contaning key information, links to teaching materials and so on. This includes a module outline, which is a document summarising the aims of the module, the teaching schedule, and the assessment requirements. You should make sure you read the outline for each module before it starts.

If you have any questions about the module organisation or content then you should contact the module leader, listed on the module DLE page.
