---
title: "PSYC612 Outline"
---

## Current Topics in Psychology 1

PSYC612 runs for six weeks in the second half of Semester 1, following the conclusion of PSYC611.

The module is structured in two consecutive blocks of three weeks each. Each block contains four options that run in parallel, and students choose one topic from each block. Each student will therefore study two options in PSYC612, each of which will be assessed by written exam in the January exam period. Each option will be worth 50% of the credit for the module.

This is a list of the options offered in each block in the 2026/27 academic year.

Descriptions of each topic can be found via the menu.

### PSYC612 Block A

1.  Julie Ji -- Harnessing the human imagination

2.  Jaysan Charlesford -- Reducing prejudice

3.  Caroline Floccia -- How do children learn to talk?

4.  Chris Mitchell -- Counselling and psychotherapy

### PSYC612 Block B

5.  Gustav Kuhn -- The misdirected mind

6.  Giorgio Ganis -- Cognitive and brain basis of deception

7.  Gray Atherton -- Neurodevelopmental conditions: Theories and practice

8.  Alison Bacon -- Criminals in the making
