---
title: "PSYC614 Outline"
---

## Current Topics in Psychology 2

PSYC614 runs for six weeks in the second half of Semester 2, following the conclusion of PSYC613.

The module is structured in two consecutive blocks of three weeks each. Each block contains four options that run in parallel, and students choose one topic from each block. Each student will therefore study two options in PSYC614, each of which will be assessed by written exam in the May exam period. Each option will be worth 50% of the credit for the module.

This is a list of the options offered in each block in the 2026/27 academic year.

Descriptions of each topic can be found via the menu.

### PSYC614 Block A

1.  Charles Or -- Perception of faces

2.  Farid Pazhoohi -- Attractiveness: What, why, and how?

3.  Liam Cross -- Social cognition in action

4.  Patricia Kanngiesser -- Social norms

### PSYC614 Block B

5.  Chris Berry -- Memory, amnesia, and awareness

6.  Denis Tatone -- Sociologists in the crib: How infants and children represent social relations, structures, and groups

7.  Sonja Heintz -- The psychology of humour

8.  Andrea Pisauro -- Psychology of AI and mental health in human-robot interactions
