---
title: "Results"
---

You will receive your results at the end of the year.

Once all your work has been marked, two exam boards meet in June. The first is the subject panel, which considers the marks for each module and confirms that the marks are appropriate. The second is the award board, which looks at the results for each individual student and makes decisions about progression from one stage to the next, as well as degree classifications for final year students. Both these exam boards include external examiners - academics from other universities whose job is to ensure that our procedures are appropriate and comparable to other institutions.

Results are sent to students once both these exam board meetings have taken place. Information about how you can access your results is provided here: <https://www.plymouth.ac.uk/student-life/your-studies/essential-information/results-guidance-notes>

### Progression

To progress from one stage to the next, students must achieve 120 credits for the stage on which they are enrolled. Each stage of our programmes contains 120 credits of modules, so you need to pass all of them to have enough credits.
