---
title: "Scholarship Standards"
---

It is important that in your assessments you explain material and express arguments in your own words, while citing clearly the sources of evidence or ideas. Work that is simply a list of quoted or paraphrased material with little intellectual input from you (e.g. your own interpretation of the subject) will receive a low mark. Extensive paraphrasing of someone else's work, whether another student's or a published author's, is unlikely to pass.

### Referencing guidelines

When psychologists write articles, reports or book chapters, they use a very specific set of conventions to reference the work of other people. This set of conventions is called the APA (American Psychological Association) style. As an undergraduate you are required to use this style when you write your assessments.

There are two things that you need to do. The first is to use in-text citations when you write about somebody else's ideas or findings. The second is to include a references section at the end of your work that gives a detailed reference for each in-text citation. In essence, the in-text citation tells the reader whose work it was, and the reference list tells us where to find that work.

The formatting of references may seem a little picky at first. However, there are very sound reasons for the rules which the APA has devised. Essentially, the rules are designed to enable the reader to find the original reference easily. You should follow these rules in all work which you submit for psychology modules. They are based on the guidelines of the APA publication: Publication Manual of the American Psychological Association, Seventh Edition (2020).

We have an online guide to APA style, that tells you how to format your references and citations: <https://plymouth.libguides.com/referencing>

Make sure you familiarize yourself with these guidelines and use this guide for reference.
