---
title: "School Facilities"
---

The School has several facilities available to you: laboratories, computer facilities and study spaces, and the test library.

### Laboratories

The School laboratories and facilities are located on floors 1, 2, and 3 in the Link Building. The facilities and equipment are managed by the School Technical Office which is in Room 109 Link Building.

You can email the technical office at: [tech.psy\@plymouth.ac.uk](mailto:tech.psy@plymouth.ac.uk){.email} or phone 01752 584815.

### Computer and study rooms

The University provides open access computer suites in the Library and Babbage buildings.

We also have Link 301, which belongs to the School and has some open-access hours in addition to its function as a workshop space.

In addition, the computers and tables in Link 106/107 are available for Psychology student use when the room is not in use for workshops or other classes or meetings. Please check the timetable on the door before entering and leave promptly when the room is about to be used for a timetabled session. It is very distracting to a class to barge in in the middle - always check before entering.

Full details of all laboratory facilities within the School of Psychology can be found on the [School web pages](https://www.psy.plymouth.ac.uk/home/).

### Test library

The School of Psychology Test Library is available to students looking to use tests for their research and is free of charge. The library consists of around 400 tests and scales and the list of tests available can be checked on-line at <https://www.psy.plymouth.ac.uk/PsychometricTests>\
To borrow tests please get in touch with the Information Assistant, Fiona Trembath for advice: [fiona.trembath@plymouth.ac.uk](mailto:fiona.trembath@plymouth.ac.uk){.email}
