---
title: "Student Representation"
---

Your experiences matter to us -- much of what we do is aimed at helping you learn, so we need to know whether we are doing the right things. The School of Psychology is a learning community, and students should consider themselves active participants.

When things go wrong or could be made even better than they are now, it is quite likely that you will spot it before we do. It is therefore important that you let us know when there are problems. These problems vary in how easily they can be addressed. Some can be dealt with straight away once they are brought to the attention of the right person, while other problems require more detailed consideration and widespread discussion, so they inevitably take longer to fix. Sometimes they are large enough to warrant a major course overhaul and may not be fixed in time to benefit you. However, such changes to the course will benefit those who follow on in the future.

Inevitably, there are some problems that are a consequence of resource limitations or external constraints, and we may not be able to do much about them. In these cases we will at least be able to let you know the reasons why those problems exist. In any event, it is important that you let us know what you think, and you can be sure that your views will be an important part of any decision making process.

### Student representatives

Course representatives are the most important channels of information for your views. The representatives serve an invaluable function. We take what they say very seriously, and we directly involve them in as much decision making as possible. For example, they constitute a major voice on the Undergraduate Programme Committee (see below).

It is important that you use your representatives to the full. In general the representatives undertake a lot of work, much of which is unseen by the majority of students. If you have an issue you can discuss it with one of your stage representatives, and they can approach an appropriate member of staff to explore what can be done about the issue.

At the beginning of each academic year, students in each stage will be canvassed for volunteers to take on the role of student representative. The representatives for each stage then share out the responsibilities which go with the role. For example, one person might be good at organising meetings and summarising what happens at meetings whereas someone else might be better at speaking out at committees. One of the main responsibilities of the role is to communicate with the student body and to represent the views of the stage to those with operational responsibility for the programmes, usually at the Undergraduate Programme Committee.

Once they are appointed, a list of your student representatives will be posted in the "Student representation" section of the [School of Psychology DLE page](https://dle.plymouth.ac.uk/course/view.php?id=66067).

### Undergraduate Programme Committee

Student representatives from each stage sit on the School's Undergraduate Programme Committee (UPC). The UPC usually meets twice per semester, and considers a range of matters relating to the undergraduate programmes. This is where student reps tell staff about the good and bad things going on with our courses. We consider each issue and the appropriate course of action. As well as discussing this feedback, the committee considers other programme issues (e.g. potential changes to the curriculum) and involves reps in this decision-making process.

UPC is chaired by the undergraduate Programme Lead, and is attended by other staff with roles that are relevant to the programme: the Student Liaison, Senior Tutor, Assessments Officer, MPysch Programme Leads, Faculty Administrator, and staff from the library and Technical Office.

Following each meeting of UPC, the Programme Lead will provide a summary of the discussion and any actions that are planned in response to feedback.
