---
title: "Submitting Coursework"
---

This section applies ONLY to Psychology modules. If you are taking modules in other schools then you need to check their submission procedures carefully.

Much of your coursework will be submitted online, using the DLE. For each piece of coursework there is a deadline. It is very important that work is submitted on or before the deadline.

There is a specific procedure which you must follow when submitting work. If this procedure is not followed then the work may not be credited as having been submitted. When you submit your work, you are responsible for ensuring that it has been received and logged correctly.

### Late submissions

Each deadline will have a specific time, clearly stated. You are strongly advised to submit your work well before this time as a submission even one second after the deadline is automatically deemed late by the coursework submission system. For example, if the deadline is listed as midday then you must submit your work by 12:00:00, i.e. the second after 11:59:59. If you submit at 12:00:01, even though your clock may say the time is 12:00, this will count as a late submission.

Coursework will be accepted if the deadline for that piece of work has passed. However, the work will be deemed late and will receive a maximum mark of 40% if submitted no later than 24 hours after the deadline, or 0% if submitted later than that. Nevertheless, the work will be handed back with feedback.

There may be occasions where you believe that there were good reasons for failing to submit coursework by the deadline. Circumstances that give rise to such occasions and that can be backed up with corroborating evidence are known as extenuating circumstances. There is a specific procedure for applying for extenuating circumstances which must be followed if you want them taken into account (see section on [extenuating circumstances](https://plymouthpsychology.github.io/handbooks/extenuating_circumstances.html) later in this guide).

Please note that no member of staff in the School of Psychology can give you an extension for a piece of coursework - you must follow the procedure for extenuating circumstances outlined later in this guide.

### Preparing your submission

For each piece of coursework, you will be provided with a template. This template will have the correct line spacing, font, font size, margins etc. already set up for you. It's important that you don't change these settings, because they ensure two things. Firstly, they ensure that we have the space to write feedback on your work. Secondly, they ensure that each page of text, even if submitted by different students, contains a comparable number of words. This in turn allows us to give meaningful guidance on the length of each assignment.

Ensure that you complete all of the information on the cover sheet on the first page of this template. You should ensure that you enter your student registration number (SRN) in the header.

On each module's DLE page you will find a link through which you can submit coursework for that module. All coursework must be submitted as a single portable document format (PDF) file unless instructed otherwise.

There is a penalty for submitting in a different format, typically one grade. For example, if the marker thought an essay was worth a 'B', but the student had submitted in .docx rather than .pdf format, the essay would be awarded a B-. This penalty reflects the additional workload created by work submitted in the wrong format.

When preparing your work for submission you should name the PDF you wish to submit in according with the following scheme:

ModuleCode_SRN_AssignmentName.pdf

For example:

PSYC421_12345678_Practical.pdf

would be student 12345678's practical report for PSYC421.

### How to submit coursework

To submit your work, follow the link for that assignment. You will need to check the declaration box to confirm that the work is your own. To upload your PDF document drag the file into the box that contains the text "You can drag and drop files here to add them". As your work uploads you will see a progress bar that may take a few moments to complete. When the upload is complete the progress bar will be replaced by a file icon. You can then click on the "Save Changes" button to submit your work. Clicking on "Save Changes" whilst the progress bar is still present may result in your work not being submitted correctly. Upon successful submission you will receive a receipt via email.

Work may be submitted as many times before the deadline as you wish to enable you to improve your work. If you feel you need to work on a piece of coursework right up until the final deadline you should make use of this facility by uploading an earlier version of your work well before the deadline. You can always replace this earlier version an unlimited number of times up until the deadline. However, if you attempt to resubmit work after the deadline it will be marked as late.
