---
title: "Support Services"
---

The University provides a wide range of support services including counselling, disability support, library services, medical and wellbeing support, and so on. These are detailed here.

We also maintain a section detailing support services on the [programme DLE page](https://dle.plymouth.ac.uk/course/view.php?id=38727).

You may make use of these services directly or, in some instances, your personal tutor may refer you to them.

You can also visit the Student Hub on the ground floor of the library building for more advice.

### Students' Union Advice Centre

The Advice Centre is independent form the University and therefore can provide confidential and free advice and support to you whilst you are studying.

The Advice Centre provides advice on the University's regulations and procedures including appeals, complaints, Disciplinaries and the Study Wellbeing and Review policy; Student Finance England queries; Housing advice; Consumer issues and we are the only the organisation within the city that deals with how welfare benefits interact with student finance and can provide full benefit calculations for students.

We are open all year round, although it is always best to check our website during vacation times as we may be running a reduced service. We are situated on the first floor of the SU building on the Plymouth Campus and offer advice through drop in sessions; appointments which can be booked at <http://www.upsu.com/advice>

Telephone: 01752 588373 or 0800 953 0155

Email: [advice\@su.plymouth.ac.uk](mailto:advice@su.plymouth.ac.uk){.email}

### Special Educational Needs

If you have Special Educational Needs then it is important that the School and the University knows about them. You can contact the University's [Disability Services](https://www.plymouth.ac.uk/services/impairments-health-conditions-and-disability), which can advise you on the likely impact of your particular needs on your academic study, and on what steps we can take to alleviate them.

It is often possible to recommend specialist facilities, support, procedures or equipment that can help to make academic study more accessible. Please alert your personal tutor as to your needs as soon as possible so that we can ensure that you see Disability Services and get any support that would be useful for you. You can also find out more via the Student Portal.
