---
title: "Workload"
---

There is a lot more to being a full-time student than will appear on your timetable. On average, only a third of your week will be spent attending scheduled teaching sessions. You will spend the remainder reading textbooks and research papers, working with other students, working on assignments, and preparing for workshops and other meetings.

Not every session will appear on your timetable. For instance, you will be required to meet with your personal tutor. We will give you clear information about any non-timetabled 
sessions that you need to attend, normally by emailing you using your university address.

Officially, a 20-credit module is designed to require 200 hours of work, divided between formal teaching, 
independent study, and assessment. The modules you take each year therefore require 1200 hours of effort in total, which results in an average of 40 hours per week across the two semesters. You should take 
this workload into account when planning part-time work during term-time; undertaking a degree means that you are in full-time education.
