---
title: "Marks"
---

Each piece of summative work will receive a mark that will count towards your overall mark for that module. In turn, your module marks will determine your degree classification. More information on this is provided in the section describing how degrees are awarded.

As a guide, a pass mark is anything above 40%. Marks from 40% to 49% correspond to a third class degree, marks from 50% to 59% correspond to a 2:2, and marks from 60% to 69% correspond to a 2:1. Marks of 70% or higher are equivalent to a first class standard of work.

The mark you receive will usually be a percentage score. Where work is marked using categorical grades (e.g. A-, C+) these will be converted into percentages using a standard table, provided here.

| Grade | Percentage |
|-------|------------|
| A+    | 100        |
| A     | 88         |
| A-    | 77         |
| B+    | 68         |
| B     | 65         |
| B-    | 62         |
| C+    | 58         |
| C     | 55         |
| C-    | 52         |
| D+    | 48         |
| D     | 45         |
| D-    | 42         |
| F+    | 38         |
| F     | 25         |
| F-    | 15         |
| N     | 0          |

An assignment or exam might consist of more than one piece of work marked in this way, in which case your mark will be an aggregate of the separate grades in the proportions specified in the module outline.

Note that the first class grades (A+, A, A-) are spaced further apart on the percentage scale than grades in the lower classes. This is designed to recognise the achievements of students who submit at least some first class work, by effectively giving first class marks more weighting when marks are aggregated together.

### Receiving your mark

If you are unhappy with your mark, you cannot ask for it to be re-marked simply because you question the marker's academic judgement. If a clerical error (such as entering an incorrect grade) has been made then the mark can be corrected provided we are made aware of the problem.

If you have a question about a grade you have been awarded, in the first instance contact the module leader or the person who set the work to discuss it (e.g. during their office hours). It would be helpful to bring a copy of the work and feedback you have received, and to highlight any areas of concern. In most cases the module leader will be able to explain the mark awarded or, where an error has occurred, correct the mark immediately.

You should always keep a copy of the coursework which you have submitted. Once you have had your work returned you should also keep the returned work and the feedback sheet with the grade awarded. Evidence of the original mark awarded to you is important if the Faculty needs to correct or add missing marks to your overall mark profile.

You should note that all marks you receive on returned coursework are provisional until agreed by the Subject Assessment Panel in June. Although it is unlikely, it is possible for the marks which you have received for a piece of work to be changed by this panel. Your end of year transcript will show your final agreed marks for each module which you have taken.
